name: minimum tests (API version)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: 0.9.8
      env:
        PYTHONPATH: .
        RTR_SCGI_SOCKET_PATH: ./.rtorrent.sock
        RTR_SYSTEM_CLIENT_VERSION: 0.9.8
        RTR_SYSTEM_API_VERSION: 10
      run: |
        7zr e ./test/deps/rtorrent-0.9.8.7z
        ./rtorrent-0.9.8 -n -o system.daemon.set=true -o network.scgi.open_local=./.rtorrent.sock &
        pytest ./test/api_version_test.py
        kill -9 `pidof rtorrent-0.9.8`
    - name: 0.9.7
      env:
        PYTHONPATH: .
        RTR_SCGI_SOCKET_PATH: ./.rtorrent.sock
        RTR_SYSTEM_CLIENT_VERSION: 0.9.7
        RTR_SYSTEM_API_VERSION: 9
      run: |
        7zr e ./test/deps/rtorrent-0.9.7.7z
        ./rtorrent-0.9.7 -n -o system.daemon.set=true -o network.scgi.open_local=./.rtorrent.sock &
        pytest ./test/api_version_test.py
        kill -9 `pidof rtorrent-0.9.7`
    - name: setup env 0.9.6
      run: |
        mkdir -p ~/.terminfo/s
        cp ./test/deps/xterm ~/.terminfo/s/screen
        sudo mkdir -p /run/screen
        sudo chmod 777 /run/screen
    - name: 0.9.6
      env:
        TERM: screen
        PYTHONPATH: .
        RTR_SCGI_SOCKET_PATH: ./.rtorrent.sock
        RTR_SYSTEM_CLIENT_VERSION: 0.9.6
        RTR_SYSTEM_API_VERSION: 9
      run: |
        7zr e ./test/deps/rtorrent-0.9.6.7z
        screen -dm ./rtorrent-0.9.6 -n -o network.scgi.open_local=./.rtorrent.sock
        pytest ./test/api_version_test.py
        kill -9 `pidof rtorrent-0.9.6`
