name: minimum tests (API version)

on: [push]

env:
  RTORRENT_STATIC_URL: https://github.com/Trogious/rtorrent-static/releases/download/v0.16.22.-static/rtorrent-static-v0.16.22.txz

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: get rtorrent
      run: |
        curl -sSfL -o /tmp/rtorrent.txz "$RTORRENT_STATIC_URL"
        tar -xJf /tmp/rtorrent.txz -C /tmp
        chmod +x /tmp/rtorrent-static
    - name: run tests
      env:
        PYTHONPATH: .
        RTR_SCGI_SOCKET_PATH: ./.rtorrent.sock
        RTR_SYSTEM_CLIENT_VERSION: 0.16.22
        RTR_SYSTEM_API_VERSION: 26
      run: |
        mkdir -p dl
        /tmp/rtorrent-static -n -o system.daemon.set=true -o directory.default.set=$PWD/dl -o network.scgi.open_local=./.rtorrent.sock &
        pytest ./test/api_version_test.py
        kill -9 `pidof rtorrent-static`
