name: main test suite

on: [push]

env:
  RTORRENT_STATIC_URL: https://github.com/Trogious/rtorrent-static/releases/download/v0.16.22.-static/rtorrent-static-v0.16.22.txz

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: get rtorrent
      run: |
        curl -sSfL -o /tmp/rtorrent.txz "$RTORRENT_STATIC_URL"
        tar -xJf /tmp/rtorrent.txz -C /tmp
        chmod +x /tmp/rtorrent-static
    - name: run tests
      env:
        PYTHONPATH: .
        RTR_SCGI_SOCKET_PATH: ./.rtorrent.sock
        RTR_SYSTEM_CLIENT_VERSION: 0.16.22
        RTR_SYSTEM_API_VERSION: 26
      run: |
        mkdir -p dl
        /tmp/rtorrent-static -n -o system.daemon.set=true -o directory.default.set=$PWD/dl -o network.xmlrpc.size_limit.set=2097152 -o throttle.global_down.max_rate.set=1024 -o throttle.global_up.max_rate.set=1024 -o network.listen.port.range.set=22400-22400 -o network.scgi.open_local=./.rtorrent.sock -o "load.normal=test/deps/torrents/*.torrent" &
        ./start.sh &
        pytest ./test
        wss_pid=`cat ./wss_server.pid`
        kill $wss_pid
        sleep 1
        test -f ./wss_server.pid && kill -9 $wss_pid
        kill -9 `pidof rtorrent-static`
  deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v7
    - name: set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-minifier
    - name: assemble package
      id: assemble_package
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        RTDIR_V=${{github.event.repository.name}}-$TAG_NAME
        RTDIR=$RTDIR_V/${{github.event.repository.name}}
        mkdir -p $RTDIR/plugins
        cp requirements.txt $RTDIR_V/
        sed -i "s/__RTR_VERSION_PLACEHOLDER__/$TAG_NAME/" server_wss.py
        for f in diffs.py model.py remote.py rpc.py scgi.py server_wss.py utils.py; do pyminify $f > $RTDIR/$f; done
        for f in plugins/*.py; do pyminify $f > $RTDIR/$f; done
        sed 's/server_wss\.py/${{github.event.repository.name}}.pyz/' ./start.sh > $RTDIR_V/start.sh
        cd $RTDIR_V
        chmod 755 ./start.sh
        python -m zipapp ${{github.event.repository.name}} -m server_wss:main
        du -shc *
        rm -rf ./${{github.event.repository.name}}
        cd ..
        tar -czvf $RTDIR_V.tgz $RTDIR_V
        du -shc $RTDIR_V.tgz
        echo "package_name=$RTDIR_V.tgz" >> "$GITHUB_OUTPUT"
    - name: create release and upload package
      uses: softprops/action-gh-release@v2
      with:
        files: ${{steps.assemble_package.outputs.package_name}}
